{
 "title": "Health-check",
 "description": "Current and avg. KPI-s. Expects 'get_load_average' and 'backends'  helpers to be installed on the monitored DB.",
 "tags": [ "pgwatch" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "query": "SELECT DISTINCT dbname FROM admin.all_distinct_dbname_metrics ORDER BY 1;"
   },
   { "name": "online_interval", "label": "Max. age for 'online' metrics", "query": "1m,3m,5m,10m,15m" }
  ]
 },
 "panels": [
  {
   "title": "Instance state",
   "type": "singlestat",
   "description": "PRIMARY - accepting writes, REPLICA - read-only",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_stats",
     "rawSql": "SELECT\n  time,\n  (data->'in_recovery_int')::int\nFROM\n  wal\nWHERE\n  time > now() - '$online_interval'::interval\n  AND dbname = '$dbname'\nORDER BY time DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Instance uptime",
   "type": "singlestat",
   "description": "Time from last Postgres process restart.  < 5m Error, < 30m Warn thresholds by default",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "rawSql": "SELECT\n  time,\n  (data->'postmaster_uptime_s')::int\nFROM\n  wal\nWHERE\n  time > now() - '$online_interval'::interval\n  AND dbname = '$dbname'\nORDER BY time DESC\nLIMIT 1\n",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "PG version num.",
   "type": "singlestat",
   "description": "\"SHOW server_version_num;\"\n110005 => 11.5",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "replication_slots",
     "rawSql": "select time, (data->'server_version_num')::int8 as value from settings where dbname = '$dbname' and $__timeFilter(time) order by time desc limit 1;"
    }
   ]
  },
  {
   "title": "Longest query runtime",
   "type": "singlestat",
   "description": "Longest query duration during last $online_interval",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "backends",
     "rawSql": "SELECT\n  0 AS time,\n  max((data->'longest_query_seconds')::int)\nFROM\n  backends\nWHERE\n  time > now() - '$online_interval'::interval\n  AND dbname = '$dbname'\n",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "singlestat",
   "description": "Connected sessions, including Postgres internal processes like Autovacuum. < 1 Warn / > 300 Error thresholds by default",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "rawSql": "SELECT\n  time,\n  (data->'numbackends')::int\nFROM\n  db_stats\nWHERE\n  time > now() - '$online_interval'::interval\n  AND dbname = '$dbname'\nORDER BY time DESC\nLIMIT 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Max. connections",
   "type": "singlestat",
   "description": "\"max_connections\" configuration setting. Changing requires re-start. 500/1000 Warn / Error thresholds by default",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "rawSql": "SELECT\n  time,\n  (data->'max_connections')::int\nFROM\n  settings\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nORDER BY time DESC\nLIMIT 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Blocked sessions",
   "type": "singlestat",
   "description": "Max number of queries waiting on resources locked by other sessions.  1 Warn / 5 Err thresholds by default",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "backends",
     "rawSql": "SELECT\n  0 as time,\n  max((data->'waiting')::int)\nFROM\n  backends\nWHERE\n  $__timeFilter(time, $online_interval)\n  AND dbname = '$dbname'",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Shared Buffers hit pct.",
   "type": "singlestat",
   "description": "Shared Buffers is the Postgres -managed file cache and 90%+ is what you normally want to see for best performance.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 2 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "rawSql": "select\n  time,\n  ((hit-hit_lag)::numeric / ((hit-hit_lag) + (read-read_lag)))*100 as \"Shared buffers hit ratio\"\nfrom (\n        select \n          (data->>'blks_hit')::int8 as hit, lag((data->>'blks_hit')::int8) over w as hit_lag,\n          (data->>'blks_read')::int8 as read, lag((data->>'blks_read')::int8) over w as read_lag,\n          (data->>'xact_rollback')::int8 as roll, lag((data->>'xact_rollback')::int8) over w as roll_lag,\n          (data->>'xact_commit')::int8 as comm, lag((data->>'xact_commit')::int8) over w as comm_lag,\n          time\n        from db_stats\n        where dbname = '$dbname' and $__timeFilter(time)\n        window w as (order by time)\n) x\nwhere hit > hit_lag or read > read_lag\norder by 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "TX rollback pct. (avg.)",
   "type": "singlestat",
   "description": "0.5% Warn / 1% Error thresholds by default",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "rawSql": "select\n  $__timeGroup(time, $online_interval),\n  max((roll-roll_lag)::numeric / ((roll-roll_lag) + (comm-comm_lag)))*100 as \"TX rollback ratio\"\nfrom (\n  select\n      time,\n      (data->>'xact_rollback')::int8 as roll, lag((data->>'xact_rollback')::int8) over w as roll_lag,\n      (data->>'xact_commit')::int8 as comm, lag((data->>'xact_commit')::int8) over w as comm_lag\n  FROM\n      db_stats\n  WHERE\n    $__timeFilter(time)\n    AND dbname = '$dbname'\n    window w as (order by time)\n) x\nWHERE comm > comm_lag or roll > roll_lag\nGROUP BY 1\nORDER BY 1 DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "TPS (avg.)",
   "type": "singlestat",
   "description": "Transactions per Second. Last $online_interval average. <0.1 % Error / < 1.0 Warn thresholds by default",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 4 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "rawSql": "select\n  $__timeGroup(time, $online_interval),\n  avg( ((roll-roll_lag) + (comm-comm_lag)) / extract(epoch from (time - time_lag))  )\nfrom (\n  select\n      time, lag(time) over w as time_lag,\n      (data->>'xact_rollback')::int8 as roll, lag((data->>'xact_rollback')::int8) over w as roll_lag,\n      (data->>'xact_commit')::int8 as comm, lag((data->>'xact_commit')::int8) over w as comm_lag\n  FROM\n      db_stats\n  WHERE\n    $__timeFilter(time)\n    AND dbname = '$dbname'\n    window w as (order by time)\n) x\nWHERE (comm > comm_lag or roll > roll_lag) and time > time_lag\nGROUP BY 1\nORDER BY 1 DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "QPS (avg.)",
   "type": "singlestat",
   "description": "Queries per Second based on  \"pg_stat_statements\" extension info. Last $online_interval avg. < 0.1 Error / < 1 Warning thresholds by default",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 4 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu_load",
     "rawSql": "select\n  $__timeGroup(time, $online_interval),\n  avg( (c - c_lag) / extract(epoch from time - time_lag)) as qps\nfrom (\n        select \n          (data->>'calls')::int8 as c, lag((data->>'calls')::int8) over w as c_lag,\n          time, lag(time) over w as time_lag\n        from stat_statements_calls\n        where dbname = '$dbname' and $__timeFilter(time)\n        window w as (order by time)        \n) x\nwhere c >= c_lag and time > time_lag\ngroup by 1\norder by 1 desc\nlimit 1\n"
    }
   ]
  },
  {
   "title": "\"Idle in TX\" count",
   "type": "singlestat",
   "description": "Transactions opened but where no queries are being executed.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "backends",
     "rawSql": "SELECT\n  0 as time,\n  max((data->'idleintransaction')::int)\nFROM\n  backends\nWHERE\n  time > now() - '$online_interval'::interval\n  AND dbname = '$dbname'\n",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "DB size (last)",
   "type": "singlestat",
   "description": "Size for selected DB only",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "rawSql": "SELECT\n  time,\n  (data->'size_b')::int8\nFROM\n  db_size\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nORDER BY time DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "DB size change (diff.)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 6 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "rawSql": "select\n  time,\n  last_value-first_value as size_diff\nfrom (\n  select\n    time,\n    first_value((data->>'size_b')::int8) over w,\n    last_value((data->>'size_b')::int8) over w\n  from\n    db_size\n  where \n    dbname = '$dbname' and $__timeFilter(time)\n  window w as (\n     order by time rows BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING\n  )\n) x\norder by 1 desc\nlimit 1"
    }
   ]
  },
  {
   "title": "DATADIR disk space left",
   "type": "singlestat",
   "description": "Assumes get_psutil_disk wrapper being installed. 10/50GB Warn/Error thresholds by default",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_changes",
     "rawSql": "select\n  time,\n  (data->'free')::int8\nfrom\n  psutil_disk\nwhere \n  dbname = '$dbname' and $__timeFilter(time)\n  and tag_data->>'dir_or_tablespace' = 'data_directory'\norder by 1 desc\nlimit 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Query runtime (avg.)",
   "type": "singlestat",
   "description": "Last $online_interval avg. based on \"pg_stat_statements\" info.  > 0.5s Warning / > 5s  Error thresholds by default",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 6 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu_load",
     "rawSql": "select\n$__timeGroup(time, $online_interval),\navg(case when c = c_lag then 0 else (tt-tt_lag)::numeric / (c-c_lag) end) as \"avg_query_runtime\"\nfrom (\n\n        select \n          (data->>'total_time')::float8 as tt, lag((data->>'total_time')::float8) over w as tt_lag,\n          (data->>'calls')::int8 as c, lag((data->>'calls')::int8) over w as c_lag,\n          time\n        from stat_statements_calls\n        where dbname = '$dbname' and $__timeFilter(time)\n        window w as (order by time)\n) x\nwhere c >= c_lag and tt >= tt_lag\ngroup by 1\norder by 1 desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Config change events",
   "type": "singlestat",
   "description": "Server configuration changes.  >1 Warn thresholds by default",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_changes",
     "rawSql": "SELECT\n  0 as time,\n  count(*)\nFROM\n  configuration_changes\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\n",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Table changes",
   "type": "singlestat",
   "description": "Number of DDL changes i.e. new or changed tables, columns, functions etc.  >1 Warn thresholds by default",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 8 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_changes",
     "rawSql": "SELECT\n  0 as time,\n  count(*)\nFROM\n  table_changes\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\n",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "WAL archiving status",
   "type": "singlestat",
   "description": "Based on pg_stat_archiver. N/A when archiving is not enabled.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "365d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "archiver",
     "rawSql": "SELECT\n  time,\n  (data->'is_failing_int')::int\nFROM\n  archiver\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nORDER BY time DESC\nLIMIT 1\n",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "WAL folder size",
   "type": "singlestat",
   "description": "Transaction Log Folder size.  Assumes get_wal_size helper being installed. 1/10 GB Warn / 50  Error  thresholds by default",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 8 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu_load",
     "rawSql": "SELECT\n  time,\n  (data->'wal_size_b')::float8\nFROM\n  wal_size\nWHERE\n  time > now() - '$online_interval'::interval\n  AND dbname = '$dbname'\nORDER BY time DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Invalid / duplicate indexes",
   "type": "singlestat",
   "description": "Invalid indexes should be dropped as they're updated on DML operations but cannot be used for speeding up queries. In case multiple indexes of same structure Postgres will use the smallest so the others can be dropped. 'N/A' displayed both when no duplicate indexes or no metrics data for index_stats.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_stats",
     "rawSql": "WITH q_duplicates AS (\nSELECT\n  coalesce(sum(count-1), 0) as extra\nFROM (\nSELECT\n  tag_data->>'table_full_name' as table_full_name,\n  data->>'index_def' as index_def,\n  count(*)\nFROM\n  index_stats\nWHERE\n  time = (select max(time) from index_stats where $__timeFilter(time) AND dbname = '$dbname')\n  AND dbname = '$dbname'\nGROUP BY 1, 2\nHAVING count(*) > 1\n) x\n)\nSELECT\n  0 as time,\n  sum((data->'is_invalid_int')::int) + (select extra from q_duplicates)\nFROM\n  index_stats\nWHERE\n  time = (select max(time) from index_stats where $__timeFilter(time) AND dbname = '$dbname')\n  AND dbname = '$dbname'\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Autovacuum issues",
   "type": "singlestat",
   "description": "i.e. AUTOVACUUM disabled globally or per table.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_stats",
     "rawSql": "SELECT\n  0 as time,\n  sum(count)\nFROM (\n\nSELECT * FROM (\n\nSELECT\n  case when data->>'autovacuum' = 'off' then 1 else 0 end as count\nFROM\n  settings\nWHERE\n  dbname = '$dbname'\n  AND time > now() - '1d'::interval\nORDER BY time DESC LIMIT 1\n\n) a\n\nUNION ALL\n\nSELECT * FROM (\n\nSELECT\n  count(*)\nFROM\n  table_stats\nWHERE\n  dbname = '$dbname'\n  AND time = (select max(time) from table_stats where dbname = '$dbname')\n  AND (data->'no_autovacuum')::int = 1\n\n) b\n\n) x;"
    }
   ]
  },
  {
   "title": "Checkpoints requested",
   "type": "singlestat",
   "description": "Checkpoints should normally be performed by the background \"Checkpointer\" process. If seeing high numbers then adjusting server configuration is recommended.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "diff",
   "targets": [
    {
     "groupBy": [
      { "params": [ "365d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "bgwriter",
     "rawSql": "SELECT\n  0 as time,\n  coalesce(sum(req - req_lag), 0)\nFROM (\nSELECT\n  (data->'checkpoints_req')::int as req,\n  lag((data->'checkpoints_req')::int) over(order by time) as req_lag\nFROM\n  bgwriter\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\n) x\nWHERE req > req_lag\n",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Approx. table bloat",
   "type": "singlestat",
   "description": "Estimated extra space held by tables (excluding indexes) that would disappear after \"compacting\".",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 10 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_stats",
     "rawSql": "SELECT\n  time,\n  (data->'approx_table_bloat_b')::int8\nFROM\n  table_bloat_approx_summary_sql\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nORDER BY 1 DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "WAL per second (avg.)",
   "type": "singlestat",
   "description": "Transaction logs generation velocity.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 12 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "wal",
     "rawSql": "select\n  0 as time,\n  avg((wal-wal_lag) / (etime-lag_etime)) as \"WAL rate\"\nfrom (\n        select \n          (data->>'xlog_location_b')::int8 as wal, lag((data->>'xlog_location_b')::int8) over w as wal_lag,\n          extract(epoch from time) as etime,\n          lag(extract(epoch from time)) over w as lag_etime,\n          time\n        from wal\n        where dbname = '$dbname' and $__timeFilter(time)\n        window w as (order by time)\n) x\nwhere wal >= wal_lag and etime > lag_etime",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Temp. bytes per second (avg.)",
   "type": "singlestat",
   "description": "Postgres writes temporary files to disk when sorting / grouping  big amounts of data that doesn't fit into \"work_mem\".  10/100 MB Warn / Error by default",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 12 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "rawSql": "select\n  0 as time,\n  avg(case when tb-tb_lag > 0 then (tb-tb_lag) / (etime - lag_etime) else 0 end) as \"Temp bytes (1h rate)\"\nfrom (\n        select \n          (data->>'temp_bytes')::int8 as tb, lag((data->>'temp_bytes')::int8) over w as tb_lag,\n          (extract(epoch from time))::int8 as etime,\n          (lag(extract(epoch from time)) over w)::int8 as lag_etime\n        from db_stats\n        where dbname = '$dbname' and $__timeFilter(time)\n        window w as (order by time)\n) x\nwhere tb >= tb_lag and etime > lag_etime\n",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Longest AUTOVACUUM duration",
   "type": "singlestat",
   "description": "Long running AUTOVACUUM processes can hint at workload or configuration  problems",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 12 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_stats",
     "rawSql": "SELECT\n  0 as time,\n  max((data->'longest_autovacuum_seconds')::int8) as longest_autovacuum_seconds\nFROM\n  backends\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Seq. scans on >100 MB tables per minute (avg.)",
   "type": "singlestat",
   "description": "Frequent sequential scans on bigger tables should usually be avoided. Warn / Error thresholds: 10 / 100",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 12 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_stats",
     "rawSql": "SELECT\n  time,\n  sum((scan-scan_lag) * 60 / extract(epoch from (time-time_lag)))\nFROM (\n  SELECT\n    time, lag(time) over w as time_lag,\n    (data->'seq_scan')::int8 as scan, lag((data->'seq_scan')::int8) over w as scan_lag\n  FROM\n    table_stats\n  WHERE\n    $__timeFilter(time)\n    AND dbname = '$dbname'\n    AND (data->'table_size_b')::int8 > 100000000\n  WINDOW w AS (partition by tag_data->>'table_full_name' order by time)\n) x\nWHERE scan > scan_lag and time > time_lag\nGROUP BY 1\nORDER BY 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "INSERT-s per minute (avg.)",
   "type": "singlestat",
   "description": "On non-temporary  tables",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 14 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "rawSql": "select\n  time,\n  avg(((ins-ins_lag) * 60) / extract(epoch from time - time_lag))\nfrom (\n        select \n          (data->>'tup_inserted')::int8 as ins, lag((data->>'tup_inserted')::int8) over w as ins_lag,\n          time, lag(time) over w as time_lag\n        from db_stats\n        where dbname = '$dbname' and $__timeFilter(time)\n        window w as (order by time)\n) x\nwhere ins >= ins_lag and time > time_lag\ngroup by 1\norder by 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "UPDATE-s per minute (avg.)",
   "type": "singlestat",
   "description": "On non-temporary  tables",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 14 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "rawSql": "select\n  time,\n  avg(((upd-upd_lag) * 60) / extract(epoch from time - time_lag))\nfrom (\n        select \n          (data->'tup_updated')::int8 as upd, lag((data->'tup_updated')::int8) over w as upd_lag,\n          time, lag(time) over w as time_lag\n        from db_stats\n        where dbname = '$dbname' and $__timeFilter(time)\n        window w as (order by time)\n) x\nwhere upd >= upd_lag and time > time_lag\ngroup by 1\norder by 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "DELETE-s per minute (avg.)",
   "type": "singlestat",
   "description": "On non-temporary  tables",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 14 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "rawSql": "select\n  time,\n  avg(((del-del_lag) * 60) / extract(epoch from time - time_lag))\nfrom (\n        select \n          (data->'tup_deleted')::int8 as del, lag((data->'tup_deleted')::int8) over w as del_lag,\n          time, lag(time) over w as time_lag\n        from db_stats\n        where dbname = '$dbname' and $__timeFilter(time)\n        window w as (order by time)\n) x\nwhere del >= del_lag and time > time_lag\ngroup by 1\norder by 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Backup duration",
   "type": "singlestat",
   "description": "Based on db_stats.backup_duration_s  / pg_backup_start_time() [9.3+] function. N/A if no backup in progress.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 14 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "backends",
     "rawSql": "SELECT\n  0 as time,\n  max((data->'backup_duration_s')::int8)\nFROM\n  db_stats\nWHERE\n  $__timeFilter(time)\n  and dbname = '$dbname'",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Max. table FREEZE age",
   "type": "singlestat",
   "description": "Max. age since last VACUUM FREEZE. Could hint at problems when going into 100s of millions",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "365d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "replication_slots",
     "rawSql": "SELECT\n  0 as time,\n  max((data->'tx_freeze_age')::int8)\nFROM\n  table_stats\nWHERE\n  $__timeFilter(time)\n  and dbname = '$dbname'",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Max. XMIN horizon age",
   "type": "singlestat",
   "description": "In TX. Holds back VACUUM",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "365d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "replication_slots",
     "rawSql": "select\n  0 as time,\n  max(xmin) from (\nSELECT\n  max((data->'xmin_age_tx')::int8) as xmin\nFROM\n  replication_slots\nWHERE\n  time = (select max(time) from replication_slots where time > now() - '$online_interval'::interval AND dbname = '$dbname')\n  and dbname = '$dbname'  \nUNION ALL\nSELECT\n  max((data->'max_xmin_age_tx')::int8) as xmin\nFROM\n  backends\nWHERE\n  time = (select max(time) from backends where time > now() - '$online_interval'::interval AND dbname = '$dbname')\n  and dbname = '$dbname'\n) x",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Inactive repl. slots",
   "type": "singlestat",
   "description": "Inactive repl. slots accumulate WAL files until disk space runs out. Re-animate the replica or use  pg_drop_replication_slot() to remove the slot so that Postgres can delete the un-needed WALs.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "replication_slots",
     "rawSql": "SELECT\n  0 as time,\n  sum((data->'non_active_int')::int)\nFROM\n  replication_slots\nWHERE\n  time = (select max(time) from replication_slots where time > now() - '$online_interval'::interval AND dbname = '$dbname')\n  AND dbname = '$dbname'\n"
    }
   ]
  },
  {
   "title": "Max. replication lag",
   "type": "singlestat",
   "description": "\"Apply\" (data made visible to queries on replica)  lag in bytes",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 16 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "replication_slots",
     "rawSql": "SELECT\n  0 as time,\n  max((data->'replay_lag_b')::int8)\nFROM\n  replication\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 18 },
   "content": "<h2>Brought to you by</h2><div style=\"padding: 25px;\"><a href=\"https://www.cybertec-postgresql.com/en/\"><img src=\"https://www.cybertec-postgresql.com/wp-content/uploads/2025/02/cybertec-logo-white-blue.svg\" alt=\"Cybertec – The PostgreSQL Database Company\"></a></div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
   "content": "<br/><h3>The preset threshold values (green / yellow / red) should be reviewed / adjusted!</h3>"
  }
 ]
}