{
 "title": "Top Sprocs",
 "tags": [ "pgwatch" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "query": "SELECT DISTINCT dbname FROM admin.all_distinct_dbname_metrics WHERE metric = 'sproc_stats' ORDER BY 1;"
   },
   { "name": "top", "query": "1,3,5,10,15,20,30,40,50" }
  ]
 },
 "panels": [
  {
   "title": "By Total Runtime",
   "type": "table",
   "description": "As per  \"sproc_stats\" measurement. Needs track_functions parameter set to 'pl' on monitored DBs.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sproc_stats",
     "query": "SELECT top(\"spread\", \"function_full_name\", \"oid\", $top) FROM (SELECT spread(\"total_time\") FROM \"sproc_stats\" WHERE $timeFilter AND \"dbname\" = '$dbname' GROUP BY time(3650d), \"function_full_name\", \"oid\" fill(none) ) WHERE spread > 0",
     "rawSql": "SELECT\n  max((data->'total_time')::float8) - min((data->'total_time')::float8) as top,\n  max((data->'sp_calls')::int8) - min((data->'sp_calls')::int8) as calls,\n  tag_data->>'function_full_name' as function_full_name,\n  tag_data->>'oid' as oid\nFROM\n  sproc_stats\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nGROUP BY 3, 4\nORDER BY 1 DESC NULLS LAST\nLIMIT $top"
    }
   ]
  },
  {
   "title": "By Total Self Runtime",
   "type": "table",
   "description": "As per  \"sproc_stats\" measurement. Needs track_functions parameter set to 'pl' on monitored DBs.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sproc_stats",
     "query": "SELECT top(\"spread\", \"function_full_name\", \"oid\", $top) FROM (SELECT spread(\"self_time\") FROM \"sproc_stats\" WHERE $timeFilter AND \"dbname\" = '$dbname' GROUP BY time(3650d), \"function_full_name\", \"oid\" fill(none) ) WHERE spread > 0",
     "rawSql": "SELECT\n  max((data->'self_time')::float8) - min((data->'self_time')::float8) as top,\n  max((data->'sp_calls')::int8) - min((data->'sp_calls')::int8) as calls,  \n  tag_data->>'function_full_name' as function_full_name,\n  tag_data->>'oid' as oid\nFROM\n  sproc_stats\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nGROUP BY 3, 4\nORDER BY 1 DESC NULLS LAST\nLIMIT $top"
    }
   ]
  },
  {
   "title": "By Calls",
   "type": "table",
   "description": "As per  \"sproc_stats\" measurement. Needs track_functions parameter set to 'pl' on monitored DBs.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sproc_stats",
     "query": "SELECT top(\"spread\", \"function_full_name\", \"oid\", $top) FROM (SELECT spread(\"sp_calls\") FROM \"sproc_stats\" WHERE $timeFilter AND \"dbname\" = '$dbname' GROUP BY time(3650d), \"function_full_name\", \"oid\" fill(none) ) WHERE spread > 0",
     "rawSql": "SELECT\n  max((data->'sp_calls')::int8) - min((data->'sp_calls')::int8) as top,\n  max((data->'total_time')::float8) - min((data->'total_time')::float8) as total_time,\n  tag_data->>'function_full_name' as function_full_name,\n  tag_data->>'oid' as oid\nFROM\n  sproc_stats\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nGROUP BY 3, 4\nORDER BY 1 DESC NULLS LAST\nLIMIT $top"
    }
   ]
  },
  {
   "title": "By Avg. Runtime",
   "type": "table",
   "description": "As per  \"sproc_stats\" measurement. Needs track_functions parameter set to 'pl' on monitored DBs.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sproc_stats",
     "query": "select top(avg, \"function_full_name\", \"oid\", $top) AS top from (select mean(t) / mean(c) AS avg from (SELECT spread(\"total_time\") AS t, spread(\"sp_calls\") AS c FROM \"sproc_stats\" WHERE $timeFilter AND dbname = '$dbname' GROUP BY time(3650d), \"function_full_name\", \"oid\" fill(none) )  where $timeFilter AND c > 0 group by time(3650d),  \"function_full_name\", \"oid\" )",
     "rawSql": "SELECT\n  total_time / calls as top,\n  calls,\n  function_full_name,\n  oid\nFROM (\n  SELECT\n    tag_data->>'function_full_name' as function_full_name,\n    tag_data->>'oid' as oid,\n    max((data->'total_time')::float8) - min((data->'total_time')::float8) as total_time,\n    max((data->'sp_calls')::int8) - min((data->'sp_calls')::int8) as calls\n  FROM\n    sproc_stats\n  WHERE\n    $__timeFilter(time)\n    AND dbname = '$dbname'\n  GROUP BY 1, 2\n) x\nWHERE calls > 0\nORDER BY 1 DESC NULLS LAST\nLIMIT $top"
    }
   ]
  },
  {
   "title": "By Avg. Self Runtime",
   "type": "table",
   "description": "As per  \"sproc_stats\" measurement. Needs track_functions parameter set to 'pl' on monitored DBs.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sproc_stats",
     "query": "select top(avg, \"function_full_name\", \"oid\", $top) AS top from (select mean(t) / mean(c) AS avg from (SELECT spread(\"self_time\") AS t, spread(\"sp_calls\") AS c FROM \"sproc_stats\" WHERE $timeFilter AND dbname = '$dbname' GROUP BY time(3650d), \"function_full_name\", \"oid\" fill(none) )  where $timeFilter AND c > 0 group by time(3650d),  \"function_full_name\", \"oid\" )",
     "rawSql": "SELECT\n  total_time / calls as top,\n  calls,\n  function_full_name,\n  oid\nFROM (\n  SELECT\n    tag_data->>'function_full_name' as function_full_name,\n    tag_data->>'oid' as oid,\n    max((data->'self_time')::float8) - min((data->'self_time')::float8) as total_time,\n    max((data->'sp_calls')::int8) - min((data->'sp_calls')::int8) as calls\n  FROM\n    sproc_stats\n  WHERE\n    $__timeFilter(time)\n    AND dbname = '$dbname'\n  GROUP BY 1, 2\n) x\nWHERE calls > 0\nORDER BY 1 DESC NULLS LAST\nLIMIT $top"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "content": "<h2>Brought to you by</h2><div style=\"padding: 25px;\"><a href=\"https://www.cybertec-postgresql.com/en/\"><img src=\"https://www.cybertec-postgresql.com/wp-content/uploads/2025/02/cybertec-logo-white-blue.svg\" alt=\"Cybertec – The PostgreSQL Database Company\"></a></div>",
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  }
 ]
}