{
 "title": "PgBouncer stats",
 "tags": [ "pgwatch" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "query": "SELECT DISTINCT dbname FROM admin.all_distinct_dbname_metrics WHERE metric = 'pgbouncer_stats' ORDER BY 1;"
   }
  ]
 },
 "panels": [
  {
   "title": "TPS",
   "type": "stat",
   "description": "Current \"Transaction Per Second\" based on total_xact_count",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 7 }
   ]
  },
  {
   "title": "QPS",
   "type": "stat",
   "description": "Current \"Queries Per Second\" based on total_query_count",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 9 }
   ]
  },
  {
   "title": "Avg. query runtime",
   "type": "stat",
   "description": "Current value based on derivative of total_query_time /  total_query_count",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 11 }
   ]
  },
  {
   "title": "Pool wait time",
   "type": "stat",
   "description": "Current avg. wait time to get a connection, per query",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 8 }
   ]
  },
  {
   "title": "Incoming traffic",
   "type": "stat",
   "description": "Current Incoming traffic  based on total_received.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 10 }
   ]
  },
  {
   "title": "Outgoing traffic",
   "type": "stat",
   "description": "Based on total_sent",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 12 }
   ]
  },
  {
   "title": "TPS",
   "type": "graph",
   "description": "Based on total_query_count",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "TPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pgbouncer_stats",
     "rawSql": "select\n  $__timeGroup(time, $__interval),\n  avg((c - c_lag) / extract(epoch from time - time_lag)) as \"TPS\"\nfrom (\n        select \n          sum((data->>'total_xact_count')::int8) as c, lag(sum((data->>'total_xact_count')::int8)) over w as c_lag,\n          date_trunc('minute', time) as time, lag(date_trunc('minute', time)) over w as time_lag\n        from pgbouncer_stats\n        where dbname = '$dbname' and $__timeFilter(time)\n        group by date_trunc('minute', time)\n        window w as (order by date_trunc('minute', time))        \n) x\nwhere c >= c_lag and time > time_lag\ngroup by 1\norder by 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Pool wait time per Query",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "alias": "Pool wait time",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "query": "SELECT non_negative_derivative(mean(\"total_wait_time\")) / non_negative_derivative(mean(\"total_query_count\")) FROM \"pgbouncer_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY time($__interval) fill(none)",
     "rawSql": "select\n$__timeGroup(time, $__interval),\navg((tt-tt_lag)::numeric / (c-c_lag)) as \"Pool wait time\"\n\nfrom (\n\n        select \n          sum((data->>'total_wait_time')::float8) as tt, lag(sum((data->>'total_wait_time')::float8)) over w as tt_lag,\n          sum((data->>'total_query_count')::int8) as c, lag(sum((data->>'total_query_count')::int8)) over w as c_lag,\n          date_trunc('minute', time) as time\n        from pgbouncer_stats\n        where dbname = '$dbname' and $__timeFilter(time)\n        group by date_trunc('minute', time)\n        window w as (order by date_trunc('minute', time))\n) x\nwhere c > c_lag and tt >= tt_lag\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "QPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pgbouncer_stats",
     "rawSql": "select\n  $__timeGroup(time, $__interval),\n  avg((c - c_lag) / extract(epoch from time - time_lag)) as \"QPS\"\nfrom (\n        select \n          sum((data->>'total_query_count')::int8) as c, lag(sum((data->>'total_query_count')::int8)) over w as c_lag,\n          date_trunc('minute', time) as time, lag(date_trunc('minute', time)) over w as time_lag\n        from pgbouncer_stats\n        where dbname = '$dbname' and $__timeFilter(time)\n        group by date_trunc('minute', time)\n        window w as (order by date_trunc('minute', time))        \n) x\nwhere c >= c_lag and time > time_lag\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "Incoming traffic rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Incoming rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pgbouncer_stats",
     "rawSql": "select\n  $__timeGroup(time, $__interval),\n  avg((c - c_lag) / extract(epoch from time - time_lag)) as \"Incoming rate\"\nfrom (\n        select \n          sum((data->>'total_received')::int8) as c, lag(sum((data->>'total_received')::int8)) over w as c_lag,\n          date_trunc('minute', time) as time, lag(date_trunc('minute', time)) over w as time_lag\n        from pgbouncer_stats\n        where dbname = '$dbname' and $__timeFilter(time)\n        group by date_trunc('minute', time)\n        window w as (order by date_trunc('minute', time))        \n) x\nwhere c >= c_lag and time > time_lag\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "Avg. query runtime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "alias": "Avg. runtime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"total_query_time\"), 1h) / non_negative_derivative(mean(\"total_query_count\"), 1h) FROM \"pgbouncer_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY time($__interval) fill(none)",
     "rawSql": "select\n$__timeGroup(time, $__interval),\navg((tt-tt_lag)::numeric / (c-c_lag)) as \"Avg. runtime\"\n\nfrom (\n\n        select \n          sum((data->>'total_query_time')::float8) as tt, lag(sum((data->>'total_query_time')::float8)) over w as tt_lag,\n          sum((data->>'total_query_count')::int8) as c, lag(sum((data->>'total_query_count')::int8)) over w as c_lag,\n          date_trunc('minute', time) as time\n        from pgbouncer_stats\n        where dbname = '$dbname' and $__timeFilter(time)\n        group by date_trunc('minute', time)\n        window w as (order by date_trunc('minute', time))\n) x\nwhere c > c_lag and tt >= tt_lag\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "Outgoing traffic rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Outgoing rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pgbouncer_stats",
     "rawSql": "select\n  $__timeGroup(time, $__interval),\n  avg((c - c_lag) / extract(epoch from time - time_lag)) as \"Outgoing rate\"\nfrom (\n        select \n          sum((data->>'total_sent')::int8) as c, lag(sum((data->>'total_sent')::int8)) over w as c_lag,\n          date_trunc('minute', time) as time, lag(date_trunc('minute', time)) over w as time_lag\n        from pgbouncer_stats\n        where dbname = '$dbname' and $__timeFilter(time)\n        group by date_trunc('minute', time)\n        window w as (order by date_trunc('minute', time))        \n) x\nwhere c >= c_lag and time > time_lag\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "options": {
    "content": "<h2>Brought to you by</h2><div style=\"padding: 25px;\"><a href=\"https://www.cybertec-postgresql.com/en/\"><img src=\"https://www.cybertec-postgresql.com/wp-content/uploads/2025/02/cybertec-logo-white-blue.svg\" alt=\"Cybertec – The PostgreSQL Database Company\"></a></div>"
   },
   "targets": [
    {}
   ]
  }
 ]
}