{
 "title": "AWS CloudWatch overview",
 "tags": [ "pgwatch" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "query": "regions()" },
   {
    "name": "dbname",
    "query": "dimension_values($region,AWS/RDS,CPUUtilization,DBInstanceIdentifier)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU load %",
   "type": "stat",
   "description": "The percentage of CPU utilization.\n\nUnits: Percent",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CPU %",
     "dimensions": { "DBInstanceIdentifier": "$dbname" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "period": "600",
     "query": "SELECT non_negative_derivative(mean(\"xact_commit\"), 1s) + non_negative_derivative(mean(\"xact_rollback\"), 1s) FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND  $timeFilter GROUP BY time($interval) fill(none)",
     "region": "$region",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Write IO",
   "type": "stat",
   "description": "The average number of bytes written to disk per second.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Write bytes/s",
     "dimensions": { "DBInstanceIdentifier": "$dbname" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "WriteThroughput",
     "namespace": "AWS/RDS",
     "period": "600",
     "query": "SELECT non_negative_derivative(mean(\"calls\"), 1s) FROM \"stat_statements_calls\" WHERE $timeFilter AND \"dbname\" =~ /^$dbname$/ GROUP BY time(1s) fill(none)",
     "region": "$region",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Read IO",
   "type": "stat",
   "description": "The average number of bytes read from disk per second.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Read bytes/s",
     "dimensions": { "DBInstanceIdentifier": "$dbname" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "ReadThroughput",
     "namespace": "AWS/RDS",
     "period": "600",
     "query": "SELECT last(\"size_b\")  - first(\"size_b\") FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY time(1h) fill(none)",
     "region": "$region",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Connections",
     "dimensions": { "DBInstanceIdentifier": "$dbname" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "period": "600",
     "query": "SELECT non_negative_derivative(last(\"total_time\"), 1h) / non_negative_derivative(last(\"calls\"), 1h) FROM \"stat_statements\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY time($interval) fill(none)",
     "region": "$region",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Free RAM",
   "type": "stat",
   "description": "The amount of available random access memory.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Free mem",
     "dimensions": { "DBInstanceIdentifier": "$dbname" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_bloat_approx_summary",
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "period": "600",
     "query": "SELECT \"load_5\"  FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY time(1h) fill(none)",
     "region": "$region",
     "select": [
      [
       { "params": [ "approx_free_space_b" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistic": "Average",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Free disk",
   "type": "stat",
   "description": "The amount of available storage space.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Free storage",
     "dimensions": { "DBInstanceIdentifier": "$dbname" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu_load",
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "period": "1800",
     "query": "SELECT \"load_5\"  FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY time(1h) fill(none)",
     "region": "$region",
     "select": [
      [
       { "params": [ "load_5min" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistic": "Average",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU details",
   "type": "timeseries",
   "description": "Credit balance/usage apply only to T2 instances",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU load",
     "dimensions": { "DBInstanceIdentifier": "$dbname" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "CPU credit balance",
     "dimensions": { "DBInstanceIdentifier": "$dbname" },
     "metricName": "CPUCreditBalance",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "CPU credit usage",
     "dimensions": { "DBInstanceIdentifier": "$dbname" },
     "metricName": "CPUCreditUsage",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "IOPS details",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Write ops/s",
     "dimensions": { "DBInstanceIdentifier": "$dbname" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "Read ops/s",
     "dimensions": { "DBInstanceIdentifier": "$dbname" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "IO queue depth",
     "dimensions": { "DBInstanceIdentifier": "$dbname" },
     "metricName": "DiskQueueDepth",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Disk/RAM details",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Free disk space",
     "dimensions": { "DBInstanceIdentifier": "$dbname" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "WAL size",
     "dimensions": { "DBInstanceIdentifier": "$dbname" },
     "metricName": "TransactionLogsDiskUsage",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "Free RAM",
     "dimensions": { "DBInstanceIdentifier": "$dbname" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "IO throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Write bytes/s",
     "dimensions": { "DBInstanceIdentifier": "$dbname" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "WriteThroughput",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "$region",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistic": "Average"
    },
    {
     "alias": "Read bytes/s",
     "dimensions": { "DBInstanceIdentifier": "$dbname" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "ReadThroughput",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "$region",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistic": "Average"
    },
    {
     "alias": "WAL bytes/s",
     "dimensions": { "DBInstanceIdentifier": "$dbname" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "TransactionLogsGeneration",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "$region",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Connections",
     "dimensions": { "DBInstanceIdentifier": "$dbname" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Replication lag",
   "type": "timeseries",
   "description": "For replicas only!",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Replication lag",
     "dimensions": { "DBInstanceIdentifier": "$dbname" },
     "metricName": "ReplicaLag",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "options": {
    "content": "<h2>Brought to you by</h2><div style=\"padding: 25px;\"><a href=\"https://www.cybertec-postgresql.com/en/\"><img src=\"https://www.cybertec-postgresql.com/wp-content/uploads/2025/02/cybertec-logo-white-blue.svg\" alt=\"Cybertec – The PostgreSQL Database Company\"></a></div>"
   },
   "targets": [
    {}
   ]
  }
 ]
}